In [1]:
import numpy as np

In [2]:
x = np.array([2, 5, 8])
print(x)
print(x.shape)

[2 5 8]
(3,)


In [3]:
# 1.向量转置
print(x.T)
print(x.T.shape)

[2 5 8]
(3,)


In [4]:
# 2.相加
y = np.array([1, 3, 7])
print(x + y)

[ 3  8 15]


In [5]:
# 3.向量与标量相乘
print(x * 3)

[ 6 15 24]


In [6]:
# 4.向量与向量相乘（对应位置元素相乘）
print(x*y)

[ 2 15 56]


In [9]:
# 5.向量点乘
print(x.dot(y))
print(x @ y)

73
73


In [10]:
# 6.范数
L0_norm = np.linalg.norm(x,ord=0)
print(L0_norm)
L1_norm = np.linalg.norm(x,ord=1)
print(L1_norm)
L2_norm = np.linalg.norm(x,ord=2)
print(L2_norm)

3.0
15.0
9.643650760992955
